### ISSUE TITLE
Show a nice image when link is shared on social platforms.

### ISSUE THREAD

**Issue by tadaspetra** [hungrimind/website#16]
Make this look nicer
![Screenshot 2023-04-07 at 10 25 34 AM](https://user-images.githubusercontent.com/60107328/230634745-201e24d3-8300-4db8-948d-4f732247147e.png)

**Comment by GaithAST** [comment]
https://www.hostgator.com/help/article/how-to-share-images-on-social-media

Hopefully this helps

**Comment by tadaspetra** [comment]
> https://www.hostgator.com/help/article/how-to-share-images-on-social-media
> 
> Hopefully this helps

Thank you @GaithAST, appreciate it :)
